---
all:
  children:
    controller:
      hosts:
        ansible-controller:
          ansible_host: 10.10.10.11
      vars:
        ansible_connection: local
    nexus:
      hosts:
        nexus_host:
          ansible_host: 10.10.10.10
    other:
      hosts:
        ubuntu22:
          ansible_host: 10.10.101.21
        debian12:
          ansible_host: 10.10.101.22
        almalinux9:
          ansible_host: 10.10.101.23
        rockylinux9:
          ansible_host: 10.10.101.24
        amazon_linux:
          ansible_host: 10.10.101.25
        host_not_exists:
          ansible_host: 10.10.101.26
        splunk:
          ansible_host: 10.10.101.31
vars:
  ansible_user: demouser
  ansible_password: changeme
  ansible_connection: ssh
  ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o PreferredAuthentications=password"
