---
all:
  children:
    nexus:
      hosts:
        10.10.10.10:
      vars:
        ansible_user: ubuntu
        ansible_password: changeme
    other_linux:
      hosts:
        10.10.101.21:
        10.10.101.22:
        10.10.101.23:
        10.10.101.24:
      vars:
        ansible_user: demouser
        ansible_password: changeme
    splunk:
      hosts:
        10.10.101.31:
      vars:
        ansible_user: demouser
        ansible_password: changeme
