---
- name: Create Nexus Ubuntu proxy repository
  ansible.builtin.uri:
    url: "{{ nexus_repository_url }}/service/rest/v1/repositories/apt/proxy"
    method: POST
    user: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    body: "{{ lookup('template', 'ubuntu_proxy_template.json') }}"
    force_basic_auth: true
    status_code: 201
    headers:
      Content-Type: "application/json"
    body_format: json
  register: ubuntu_proxy_response
