---
- name: Gathering minimal facts
  ansible.builtin.setup:
    gather_subset: "!all"
  ignore_errors: true
  ignore_unreachable: true
  throttle: "{{ throttling }}"
  register: facts
  async: 300
  poll: 15
